// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.svelle.pagerduty-plugin",
    "name": "Mattermost PagerDuty Plugin",
    "description": "PagerDuty integration for Mattermost - View on-call schedules and current on-call users directly within Mattermost.",
    "homepage_url": "https://github.com/svelle/mattermost-pagerduty-plugin",
    "support_url": "https://github.com/svelle/mattermost-pagerduty-plugin/issues",
    "release_notes_url": "https://github.com/svelle/mattermost-pagerduty-pluginreleases/tag/v2.3.0",
    "icon_path": "assets/pagerduty-icon.svg",
    "version": "2.3.0",
    "min_server_version": "6.2.1",
    "server": {
        "executables": {
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "darwin-arm64": "server/dist/plugin-darwin-arm64",
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "linux-arm64": "server/dist/plugin-linux-arm64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "Configure your PagerDuty integration settings below.",
        "footer": "Need help? Visit our [documentation](https://github.com/svelle/mattermost-pagerduty-plugin#configuration).",
        "settings": [
            {
                "key": "OAuthClientID",
                "display_name": "PagerDuty OAuth Client ID",
                "type": "text",
                "help_text": "The Client ID from your PagerDuty OAuth application. Create one at https://developer.pagerduty.com/apps.",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": false
            },
            {
                "key": "OAuthClientSecret",
                "display_name": "PagerDuty OAuth Client Secret",
                "type": "text",
                "help_text": "The Client Secret from your PagerDuty OAuth application.",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": true
            },
            {
                "key": "APIBaseURL",
                "display_name": "PagerDuty API Base URL",
                "type": "text",
                "help_text": "The base URL for PagerDuty API. Leave default unless using a custom PagerDuty instance.",
                "placeholder": "https://api.pagerduty.com",
                "default": "https://api.pagerduty.com",
                "hosting": "",
                "secret": false
            },
            {
                "key": "WebhookSecret",
                "display_name": "Webhook Secret (Optional)",
                "type": "generated",
                "help_text": "Secret used to verify PagerDuty webhook signatures. Auto-generated when using /pagerduty webhook setup. Set manually if configuring webhooks outside the plugin.",
                "placeholder": "",
                "default": "",
                "hosting": "",
                "secret": false
            }
        ],
        "sections": null
    }
}
`);

export default manifest;
